# Generated by Django 6.0.4 on 2026-04-11 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_nouvelles_fonctionnalites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'إنشاء'), ('modification', 'تعديل'), ('suppression', 'حذف'), ('connexion', 'دخول'), ('deconnexion', 'خروج'), ('paiement', 'دفع'), ('transfert', 'تحويل'), ('annulation', 'إلغاء')], max_length=20, verbose_name='الإجراء')),
                ('modele', models.CharField(max_length=50, verbose_name='الجدول')),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مراقبة',
                'verbose_name_plural': 'سجل المراقبة',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('rdv_confirme', 'موعد مؤكد'), ('rdv_annule', 'موعد ملغي'), ('rdv_rappel', 'تذكير بموعد'), ('analyse_prete', 'تحليل جاهز'), ('ordonnance', 'وصفة طبية جديدة'), ('transfert', 'تحويل إلى طبيب'), ('general', 'إشعار عام')], default='general', max_length=30, verbose_name='نوع الإشعار')),
                ('titre', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('lue', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('lien', models.CharField(blank=True, max_length=200, verbose_name='الرابط')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PlanningSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lun', 'الاثنين'), ('mar', 'الثلاثاء'), ('mer', 'الأربعاء'), ('jeu', 'الخميس'), ('ven', 'الجمعة'), ('sam', 'السبت'), ('dim', 'الأحد')], max_length=3, verbose_name='اليوم')),
                ('heure_debut', models.TimeField(verbose_name='بداية العمل')),
                ('heure_fin', models.TimeField(verbose_name='نهاية العمل')),
                ('actif', models.BooleanField(default=True, verbose_name='يعمل هذا اليوم')),
                ('duree_rdv', models.PositiveIntegerField(default=30, verbose_name='مدة الموعد (دقائق)')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='clinic.medecin', verbose_name='الطبيب')),
            ],
            options={
                'verbose_name': 'يوم عمل',
                'verbose_name_plural': 'جدول العمل الأسبوعي',
                'ordering': ['medecin', 'jour'],
                'unique_together': {('medecin', 'jour')},
            },
        ),
    ]
